### ISSUE TITLE
Debug why "saving" and completion badges aren't showing up

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/TI-wp-content-theme#31]
... in some cases

**Comment by limikael** [comment]
This was because the plugin was deactivated... the wp-h5p-xapi plugin had a bug before which made it spam error messages in the console, that's why i deactivated it...

However... this is fixed now!

I also made a feature so that the tickmark should show up directly upon completion of a swagifact, no need to reload the page...

Please verify that it works!
