### ISSUE TITLE
create the possibility for swagpaths to have attached lesson plans

### ISSUE THREAD

**Issue by limikael** [tunapanda/TI-wp-content-theme#37]
It should be possible to attach a lesson plan to each swagpath. This could be implemented by a new shortcode, so the swagpath pages would look like this:

```
[course]
  [h5p-course-item slug="this-is-a-course-item"]
  [h5p-course-item slug="this-is-another-course-item"]
[/course]

[lessonplan]
Here be the lesson plan...
[/lessonplan]
```

Then there would be a button on each swagpath to view the lessonplan. This button would be available if you have collected the swag associated with the swagpath (consistent with "learn, then teach others"). It would also be available to users with a certain role (e.g. author).

**Comment by mrlarso** [comment]
Lesson plans can now be added within the course shortcode:

[course lessonplan="/path/to/lessonplan.pdf"]
[/course]

A download button should appear in any course with a lesson plan included as above.

The download button should be active (and the lesson plan available) only if the user has collected swag for the course, otherwise it should be inactive.

**Comment by c3c1l1a** [comment]
There seems to be a bug. I was expecting the "Download Lesson Plan" button to be active when I finish a swagpath. That is not happening. May be am missing something?

**Comment by c3c1l1a** [comment]
Ok. working perfectly.
