### ISSUE TITLE
Mail server not functioning

### ISSUE THREAD

**Issue by mrlarso** [tunapanda/TI-wp-content-theme#43]
Cannot enter into password recovery. Receive the following error:

**The email could not be sent.
Possible reason: your host may have disabled the mail() function.**

**Comment by limikael** [comment]
There are 2 ways basically to get mail working from PHP.
- Configure sendmail.
- Use some other way and connect through a SMTP server.

The first option, to configure sendmail, is a special kind of hell. What's worse, there is not really any good ways to test if it has been configured properly. We should avoid this.

The second way is to use a SMTP server, and then install a plugin for wordpress that allows sending mail through that SMTP server. There are a few plugins for this:
- https://wordpress.org/plugins/easy-wp-smtp/
- https://wordpress.org/plugins/wp-smtp/
- https://wordpress.org/plugins/postman-smtp/

I have used the folowing and gotten it to work. However, the other ones have more installs...

https://wordpress.org/plugins/wp-mail-bank/

There are probably more... We should do some research in order to find out which one works best...

Unfortunately, I don't think the information in the description "You can use Gmail, Yahoo, Hotmail's SMTP server if you have an account with them" is accurate. It doesn't seem like gmail actually allows this anymore.

Instead, I think we need to find a cloud based SMTP service. Maybe: http://www.easy-smtp.com/

So... We need to register there and test if it works...

**Comment by neerajkamdar** [comment]
Postfix is another option: http://www.postfix.org

Or Mailgun is an SMTP service that has a free tier upto 10,000 emails which should be enough for our purpose - https://www.mailgun.com. It has a wordpress plugin too: https://wordpress.org/plugins/mailgun/

**Comment by limikael** [comment]
@neerajkamdar That is awesome info! We should certainly give that a go. Btw, have you actually used any solution "in the wild" so you can testify which one might be the best?

**Comment by neerajkamdar** [comment]
I have setup postfix on a digital ocean droplet for a client. But it is only used for outgoing messages sent by the system, not for incoming email. 

I have not used Mailgun - I have used Mandrill (a services similar to Mailgun - now that I think about it they also have a free tier of upto 12000 emails per month).

I think for this purpose postfix is the best as we don’t have to think about it once it’s installed and worry about API keys for Mandrill or Mailgun etc. 

My understanding is we only have to setup outgoing mail for the system to be able to send emails, so postfix should do the job and it’s not very difficult to setup since we don’t have to worry about incoming mail. 

If you want me to set it up, then just send me the access info for the server and I can set it up.

Thanks,
Neeraj

**Comment by limikael** [comment]
Yep, it's only for outgoing mail, the incoming mail is handled by gmail.

But you have access, right? The neeraj user should have administration rights? And that should be all that's needed to install required plugins and set them up. I wouldn't mind giving you root access to the server, but I think for this particular issue I think the ideal solution would be one where this wouldn't be needed. Am I missing something?

Anyway, it might be the case that @mrlarso (that's Mick :) ) already started working on this, so coordinate with him...

**Comment by neerajkamdar** [comment]
For postfix, we have to install it on the server - it is not affiliated with wordpress - once installed it is configured to be used for all system mail functions such as PHPs mail function. So if we decide to use Postfix then I will need server access - unless @mrlarso can set it up.

If we decide to use Mandrill or Mailgun, then I don’t think server access is necessary. I think I can setup the plugin.

Let me know which one you prefer. 

Neeraj

**Comment by mrlarso** [comment]
I haven't had too much time to look into it, but I also think postfix sounds like the best option here.  Neeraj, if you want to set it up that would be great!

**Comment by limikael** [comment]
Hm... I actually disagree... I checked out postfix and it is a server component, a replacement for sendmail. I think there is value to rely as much as possible on things that can be installed in Wordpress. So I think Mandrill or Mailgun is the best alternative.

**Comment by neerajkamdar** [comment]
Ok .. I’ll setup Mandrill or Mailgun first. If we decide to move to postfix at a later stage, we can set that up and remove the plugin. It will not cause any disruption to the system .

**Comment by mrlarso** [comment]
Cool, was just discussing with Micke and he convinced me that one of the
plugins is the best way to go :)

**Comment by neerajkamdar** [comment]
Ok .. I’ve installed Mandrill plugin and set it up. I sent myself a test password reset and it worked. 

I’ll send you the Mandrill login credentials separately.

If those who were having trouble getting emails when signing up can test this again, it would be great.

**Comment by mrlarso** [comment]
Awesome. Just tested and it's working perfectly. Thanks!

**Comment by limikael** [comment]
Alright, so @neerajkamdar and @mrlarso tested it. (Which is 2 different people, which is what we are aiming for...) So shall we close it?

**Comment by mrlarso** [comment]
I just closed it.
