### ISSUE TITLE
learning.tunapanda.org database keeps crushing

### ISSUE THREAD

**Issue by c3c1l1a** [tunapanda/TI-wp-content-theme#62]
The database keeps crushing and displays this 
![screenshot from 2016-05-18 09 09 06](https://cloud.githubusercontent.com/assets/8858461/15350096/fca9f0c0-1cdf-11e6-8a41-df5e7cdad298.png)

**Comment by usernamenumber** [comment]
Do we have access to the logs of the server where the site is hosted? If
the db connection is established by the php component, then the web server
error log might have more details.
On May 18, 2016 12:06 AM, "wangui" notifications@github.com wrote:

The database keeps crushing and displays this
[image: screenshot from 2016-05-18 09 09 06]
https://cloud.githubusercontent.com/assets/8858461/15350096/fca9f0c0-1cdf-11e6-8a41-df5e7cdad298.png

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/tunapanda/TI-wp-content-theme/issues/62

**Comment by mrlarso** [comment]
I've attached the logs that I think might be relevant. Will try digging
through them today, though not completely sure what to look for.

On Wed, May 18, 2016 at 5:06 PM, Brad Smith notifications@github.com
wrote:

> Do we have access to the logs of the server where the site is hosted? If
> the db connection is established by the php component, then the web server
> error log might have more details.
> On May 18, 2016 12:06 AM, "wangui" notifications@github.com wrote:
> 
> The database keeps crushing and displays this
> [image: screenshot from 2016-05-18 09 09 06]
> <
> https://cloud.githubusercontent.com/assets/8858461/15350096/fca9f0c0-1cdf-11e6-8a41-df5e7cdad298.png
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tunapanda/TI-wp-content-theme/issues/62
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tunapanda/TI-wp-content-theme/issues/62#issuecomment-220036678

## 

Mick Larson
Co-Founder
www.Tunapanda.org

Mick@Tunapanda.org mick@tunapanda.org
+254 (0)7-0033-2770

**Comment by mrlarso** [comment]
I guess the log files didn't attach before. Here they are. Based on this error in the mysql error log:

**[ERROR] InnoDB: Cannot allocate memory for the buffer pool**

And the threads [here](http://dba.stackexchange.com/questions/25165/intermittent-mysql-crashes-with-error-fatal-error-cannot-allocate-memory-for-t) and [here](http://www.webtrafficexchange.com/solved-mysql-crash-fatal-error-cannot-allocate-memory-buffer-pool),

I've reduced the size of the MySQL buffer pool.

Hopefully that will solve the issue, otherwise there are things we can try such as allocating swap space.

[syslog.txt](https://github.com/tunapanda/TI-wp-content-theme/files/271965/syslog.txt)
[apache2_error.log.txt](https://github.com/tunapanda/TI-wp-content-theme/files/271964/apache2_error.log.txt)
[mysql_error.log.txt](https://github.com/tunapanda/TI-wp-content-theme/files/271966/mysql_error.log.txt)

**Comment by c3c1l1a** [comment]
Database hasn't had any issues in the past few week. Closing the issue.
